### ISSUE TITLE
Users can configure backup storage

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/zeebe#10264]
Currently we support on S3 as backup store. But for future compatibility, the user must be able to specify which backup store to use and configure them. 

For S3 backup store, following parameters must be configurable
- bucket name
- S3 endpoint
- credentials

Reference #10220

**Comment by deepthidevaki** [comment]
Currently we support only s3. But in future, we may support more stores. So a user must be able to specify which store to use for backup and configure it. In addition, it might be useful to allow community contributed backup stores similar to the exporters. So the config that we define now must be extendable without breaking compatability.

For that I can think of two way of configuring it.

#### Option 1:
Similar to Exporter configuration
```
jarPath:
className:
Map<String, Object> args:
```
Example:
```
className: io.camunda.zeebe.backup.s3.S3BackupStore
args:
  bucketName:
  credentials:
  endpoint:
```
Zeebe can instantiate a backup store using the given className and arguments. This way both internally supported stores and external implementations are configured similarly. 

#### Option 2:
Differentiate between internally supported stores and external stores.

Example
```
type: s3
args:
  bucketName:
  endpoint: 
  credentials:
	
(if we support gcs in future)
type: gcs
args:
  gcp-specific-parameters:
```	
	
For external store implementations, we can define the type as external. Similar to export configuration, they should then provide the className, path and args. 
```
type: external
args:
  jarPath:
  className:
  other_args:
```
We do not have to support external implementations now. So we can define the config and implement support for it later.
