### ISSUE TITLE
Auto merge green dependabot PRs

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#10295]
**Description**

At the moment, we have to manually merge passing dependabot PRs. While there is always a risk to do so, we could at the very least enable auto merging patch releases (assuming the PR is green). I think in most cases the risk is quite low.

There are cases where dependencies do not use semantic versioning, so we can't rely on the meaning of the patch release. But in general, we rarely do more checks if our PRs are green, so I'm not sure what we gain by keeping them on a manual lifecycle.

[GitHub has some docs on how to automate merging PRs](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#enable-auto-merge-on-a-pull-request):

```yaml
name: Dependabot auto-merge patch updates
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1.1.1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Enable auto-merge for Dependabot PRs
        if: ${{ steps.metadata.outputs.update-type == 'version-update:semver-patch' }}
        run: gh pr comment "${PR_ID}" --body "bors merge"
        env:
          PR_ID: ${{github.event.pull_request.number}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

```

**Comment by korthout** [comment]
Please don’t do this will mess up any merges from bors. Why not automate approving and commenting `bors-merge` on these PRs? Then bors can auto merge for us

**Comment by npepinpe** [comment]
In the end I just want them merged, so however it's done is implementation details ;)

**Comment by npepinpe** [comment]
I've updated the above to just comment `bors merge` :+1:

**Comment by korthout** [comment]
Thanks @npepinpe in that case I'm all for it! 🚀

**Comment by npepinpe** [comment]
Unfortunately, this is a little more complicated than I thought. `gh pr merge --auto` is the magic sauce, which actually merges ONLY when all CI checks are successful. Just commenting would cause bors to start faster, before all the checks are done. So we'll have to ourselves implement this "wait until all checks are successful". Now if we had a CI top level workflow, this would be easier, since this could be a last step, but we don't, such is life :)

**Comment by npepinpe** [comment]
The other option here is, of course, to use renovate :smile:

**Comment by korthout** [comment]
Can't we do something similar to the `publish_test_results` workflow? 

```
on:
  workflow_run:
    workflows: [Tests]
    types:
      - completed
```
