### ISSUE TITLE
Benchmark workflow fails

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#11351]
**Describe the bug**

Benchmark workflow fails with: `Error: Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/runner/work/zeebe/zeebe/.github/actions/setup-zeebe'. Did you forget to run actions/checkout before running your local action?`

https://github.com/camunda/zeebe/actions/runs/3808438313/jobs/6479015772

Maybe related to https://github.com/actions/checkout/issues/692

**To Reproduce**
Not sure.

**Expected behavior**
No issues.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
<STACKTRACE>
```

</p>
</details>

**Environment:**
- OS: 
- Zeebe Version: 
- Configuration:

**Comment by Zelldon** [comment]
Nevermind the failure is expected since the ref: doesn't exist 

```
 Inputs
    name: release-0-1-x
    ref: 0.1.0
    cluster: zeebe-long-running
    cluster-region: europe-west1-b
    benchmark-load: 
```
