### ISSUE TITLE
GCS backup store can be configured

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/zeebe#11924]
Rough idea for required configuration:
```yaml
zeebe.broker.data.backup:
  store: gcs
  gcs:
    bucketName:
    basePath:
```

At least two items will be added later:
- Authentication
- Compression
