### ISSUE TITLE
Update release process documentation for go-apidiff

### ISSUE THREAD

**Issue by abbasadel** [camunda/zeebe#13133]
**Description**
Since `bros` GH Action does not work properly with `go-apidiff` (details here #12838), we have to hardcode the target branch name in [ci.yaml](https://github.com/camunda/zeebe/blob/6051e2cdd6010d3447cad7eeea8b24a7eaeb7a54/.github/workflows/ci.yml#L323) for `go-apidiff` to work properly. 

Example: 
This is the current Go Backward Compatibility settings.
```
  go-apidiff:
    name: Go Backward Compatibility
    runs-on: ubuntu-latest
    env:
      # bors-ng fails to set ${GITHUB_BASE_REF} to the target PR branch which breaks go-apidiff
      # so we use this fixed value as a workaround
      GO_CLIENT_BASE_REF: stable/8.3
```

Once we create a new minor release, we should update the following line:

```
GO_CLIENT_BASE_REF: stable/8.x
```

```[tasklist]
### Tasks
- [x] Update the release process documentation to hardcode the stable branch name in `go-apidiff` GH action when creating a new release branch.
```
