### ISSUE TITLE
Brokers on release benchmarks are failing due to OOM

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#13948]
**Describe the bug**

It looks like that we have on release benchmarks (8.0 and 8.1) failing or terminated broker pods, due to OOM.

```
8.0 - zeebe -0: Last State: Terminated Reason: OOMKilled Exit Code: 137 
8.0 - zeebe-1:   Last State: Terminated Reason: OOMKilled Exit Code: 137
8.0 - gateway: Last State: Terminated Reason: Error Exit Code: 3 
8.1:
release-8-1-x-zeebe-0 1/1 Running 2 (7d11h ago) 33d release-8-1-x-zeebe-1 1/1 Running 4 (8d ago) 33d release-8-1-x-zeebe-2 1/1 Running 1 (19d ago) 33d release-8-1-x-zeebe-gateway-5476565f47-lk4b8 1/1 Running 45 (6d22h ago) 33d release-8-1-x-zeebe-gateway-5476565f47-zppwx 1/1 Running 45 (6d23h ago) 33d 
Zeebe-0:     Last State:     Terminated       Reason:       Error Exit Code:    134
Zeebe-1: Last State: Terminated Reason: Error Exit Code: 134
Zeebe-2: Last State: Terminated Reason: Error Exit Code: 134
Zeebe-gateway:  - gateway: Last State: Terminated Reason: Error Exit Code: 3 
```

[This is also visible in the Zeebe medic overview dashboard:](https://grafana.dev.zeebe.io/d/zeebe-medic-benchmark/zeebe-medic-benchmarks?orgId=1&refresh=1m&from=now-7d&to=now&editPanel=295)

![pod-errors](https://github.com/camunda/zeebe/assets/2758593/3a7b2a05-5b39-4caf-8605-297dc0c13f5a)

**To Reproduce**

Check the release benchmarks.

**Expected behavior**

No failure due to OOM. The other release branch (8.2), works fine.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
<STACKTRACE>
```

</p>
</details>

**Environment:**
- OS: 
- Zeebe Version: 8.0, 8.1
- Configuration:

**Comment by koevskinikola** [comment]
ZPA triage:
- Currently not clear what the root cause is. Maybe it's the available memory of the machine.
- We can try to understand if the issue occurs in SaaS clusters.
- Priority is `upcoming` to prioritize investigating it in future dev iterations.
- Size is not clear, probably `medium`, as the root cause is difficult to determine.
- ZPA would like to see this resolved but doesn't currently have the capacity to look into it.

**Comment by oleschoenburg** [comment]
Looking at the 8.1 release benchmark:
Brokers repeatedly run into https://github.com/camunda/zeebe/issues/11091, likely correlated to role changes.
I've collected a [heapdump](https://github.com/camunda/zeebe/files/12438919/zeebe-0.zip) but the only thing that stood out to me was https://github.com/camunda/zeebe/pull/14012

**Comment by oleschoenburg** [comment]
The benchmark for release 8.0 had the following OOM events:

- zeebe-1 at 2023-08-11 13:31:05.024 CEST. The broker was going through multiple role transitions for partition 2 at the time.
- zeebe-0 at 2023-08-03 04:45:11.649 CEST. The broker appears to be in a steady state but is stuck in a loop trying to distribute a deployment to partition 3.


both events were initiated by k8s so we don't have a heapdump from then.

**Comment by oleschoenburg** [comment]
@npepinpe and I took a look together and we came to the conclusion that this is likely caused by two factors:
1. Older brokers use much more direct memory because of the dispatcher
2. We set memory request to 2GiB which is too low: https://github.com/zeebe-io/benchmark-helm/pull/90

**Comment by oleschoenburg** [comment]
I've also went through logs and I find several instances where java processes were getting killed because they exceeded the cgroup quota: https://cloudlogging.app.goo.gl/vV8K1dWu3smebh5V8
To me that just confirms that the underlying issue was that we requested too little memory.

**Comment by npepinpe** [comment]
Is there anything else to do here? I also did extensive benchmarking on the gateways, and honestly I found that the issue is pretty much the same. We allocate very little memory, such that spikes will cause them to restart. A restart causes requests to buffer, back off, and on restart you get another spike, and you end up in a loop.

Here is a link to the bucket I used to store the gateway's heap dumps and memory tracking summary:

https://console.cloud.google.com/storage/browser/np-gateway-oom?project=zeebe-io

Top level is a folder for each gateway pod. In there, you'll find a heap dump every time it went OOM (there's quite a lot by now), and you'll also find memory tracking summaries as "memory_2023-09-20T13:53:25Z.log", where the timestamp is the start up time of the broker. These were generated by repeatedly writing the summary in that file every minute. The idea was that when the broker crashed and restarted, we could look at the JVM's memory tracking information up to 1 minute before.

So for a node with 400Mi, 25% max RAM, you get something like (note that Ole and I discovered that the JVM's MaxRAM is not based on the request but on the limit ? I think - correct me if I'm wrong. Was it the limit or the node's RAM?)

```
7:

Native Memory Tracking:

(Omitting categories weighting less than 1KB)

Total: reserved=1570907KB +157KB, committed=169339KB +221KB

-                 Java Heap (reserved=129024KB, committed=58292KB)
                            (mmap: reserved=129024KB, committed=58292KB)
 
-                     Class (reserved=1049787KB, committed=7995KB)
                            (classes #11516)
                            (  instance classes #10831, array classes #685)
                            (malloc=1211KB #25456 +10)
                            (mmap: reserved=1048576KB, committed=6784KB)
                           : (  Metadata)
                            (    reserved=65536KB, committed=42304KB)
                            (    used=42033KB +3KB)
                            (    waste=271KB =0.64% -3KB)
                           : (  Class space)
                            (    reserved=1048576KB, committed=6784KB)
                            (    used=6619KB)
                            (    waste=165KB =2.43%)
 
-                    Thread (reserved=31833KB, committed=3181KB)
                            (thread #0)
                            (stack: reserved=31744KB, committed=3092KB)
                            (malloc=55KB #190)
                            (arena=34KB #60)
 
-                      Code (reserved=248816KB +3KB, committed=17448KB +67KB)
                            (malloc=1128KB +3KB #7007 +17)
                            (mmap: reserved=247688KB, committed=16320KB +64KB)
 
-                        GC (reserved=451KB, committed=219KB)
                            (malloc=23KB #78)
                            (mmap: reserved=428KB, committed=196KB)
 
-                  Compiler (reserved=289KB -1700KB, committed=289KB -1700KB)
                            (malloc=124KB #637)
                            (arena=165KB -1700 #5 -8)
 
-                  Internal (reserved=352KB, committed=352KB)
                            (malloc=316KB #7289 +7)
                            (mmap: reserved=36KB, committed=36KB)
 
-                     Other (reserved=8722KB, committed=8722KB)
                            (malloc=8722KB #23)
 
-                    Symbol (reserved=11409KB, committed=11409KB)
                            (malloc=10666KB #269466 +1)
                            (arena=744KB #1)
 
-    Native Memory Tracking (reserved=5286KB +145KB, committed=5286KB +145KB)
                            (malloc=317KB +115KB #4720 +1847)
                            (tracking overhead=4969KB +30KB)
 
-        Shared class space (reserved=16384KB, committed=10824KB)
                            (mmap: reserved=16384KB, committed=10824KB)
 
-               Arena Chunk (reserved=2448KB +1710KB, committed=2448KB +1710KB)
                            (malloc=2448KB +1710KB)
 
-                    Module (reserved=271KB, committed=271KB)
                            (malloc=271KB #2043)
 
-                 Safepoint (reserved=8KB, committed=8KB)
                            (mmap: reserved=8KB, committed=8KB)
 
-           Synchronization (reserved=64KB, committed=64KB)
                            (malloc=64KB #759)
 
-            Serviceability (reserved=1KB, committed=1KB)
                            (malloc=1KB #6)
 
-                 Metaspace (reserved=65752KB, committed=42520KB)
                            (malloc=216KB #142)
                            (mmap: reserved=65536KB, committed=42304KB)
 
-      String Deduplication (reserved=1KB, committed=1KB)
                            (malloc=1KB #8)
 
-           Object Monitors (reserved=8KB, committed=8KB)
                            (malloc=8KB #38)
```

To do this, I deployed the following config map and cronjob:

<details><summary>cronjob.yaml</summary>

```yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader
subjects:
- kind: ServiceAccount
  name: default
  namespace: np-gateway-oom
roleRef:
  kind: ClusterRole
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: memory-logger
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: memory-logger
              image: alpine/k8s:1.27.6
              command:
                - sh
                - -c
                - for gateway in $(kubectl get pods
                  --selector=app.kubernetes.io/component=zeebe-gateway -o name); do
                  kubectl exec ${gateway#pod/} -c zeebe-gateway -- bash -c 'pid=$(jps |
                  grep StandaloneGateway | cut -d" " -f 1); jcmd $pid VM.native_memory
                  baseline; jcmd $pid VM.native_memory summary.diff >
                  /mnt/data/${K8S_NAME}/memory.log'; done
              securityContext:
                allowPrivilegeEscalation: true
                privileged: true
          restartPolicy: OnFailure
```

</details>

I also deployed a config map with an own startup script so I could grab some runtime info to define file names:

<details><summary>configmap.yaml</summary>

```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: np-gateway-config
  namespace: np-gateway-oom
data:
  startup.sh: |
    #!/usr/bin/env bash
    set -eu -o pipefail

    HOST=$(hostname -i)
    export ZEEBE_GATEWAY_NETWORK_HOST=${ZEEBE_GATEWAY_NETWORK_HOST:-${HOST}}
    export ZEEBE_GATEWAY_CLUSTER_HOST=${ZEEBE_GATEWAY_CLUSTER_HOST:-${ZEEBE_GATEWAY_NETWORK_HOST}}

    DATA_DIR="/mnt/data/${K8S_NAME}"
    TIMESTAMP=$(date +%s)
    mkdir -p "${DATA_DIR}"
    JAVA_OPTS=${JAVA_OPTS:-""}
    export JAVA_OPTS="${JAVA_OPTS} -XX:HeapDumpPath=${DATA_DIR}/${TIMESTAMP}.hprof -XX:ErrorFile=${DATA_DIR}/${TIMESTAMP}_error.log -XX:NativeMemoryTracking=detail"

    exec /usr/local/zeebe/bin/gateway
```

</details>

Then modified the gateway deployment to mount the map/script and use it as the startup point.

Before going into the detailed memory, let's clarifying some wording.

Reserved memory the total amount of memory the JVM can potentially use. Committed memory is the amount that it's actually using right now.


Anyway, if you look at the summary, the conclusion is that, out of 400Mi/419MB requested:

1. The heap is guaranteed 129MB, but currently only using 88MB.
2. Meta space uses 45MB.
3. Threads use 3MB.
4. The code cache (JIT) is using almost 18MB.
5. Other (??) uses 8MB.
6. A bunch of smaller stuff (arena, using ~2.5MB)

Then we have a bunch of smaller stuff. But that means we have almost 100MB used by non heap or direct memory, which is close to a quarter of our total memory...

This means we have pretty much no wiggle room when brokers are slow or unresponsive and requests pile up, and we end up buffering requests...

It's very easy to get gateways out of memory. A better approach would be to eventually reject requests when you're out of memory, instead of buffering forever :upside_down_face:
