### ISSUE TITLE
Unnessesary Netty natives memory usage

### ISSUE THREAD

**Issue by aivinog1** [camunda/zeebe#14722]
**Describe the bug**

First of all: I'm not sure if it is a bug or expected but still feels strange 🙂
In my team, we have a question about memory consumption **after** our load test is finished, but this is a different story. So, we are trying to analyze what is going on with the memory of our Zeebe Broker containers and we see that (7 - is the Zeebe broker process in the Docker container):
```
root@container-id:/usr/local/zeebe# cat /proc/7/maps | grep netty
7f7cfd200000-7f7cfd212000 r-xp 00000000 00:42 233214087                  /tmp/libnetty_transport_native_epoll_x86_641630526006297879259.so (deleted)
7f7cfd212000-7f7cfd411000 ---p 00012000 00:42 233214087                  /tmp/libnetty_transport_native_epoll_x86_641630526006297879259.so (deleted)
7f7cfd411000-7f7cfd414000 r--p 00011000 00:42 233214087                  /tmp/libnetty_transport_native_epoll_x86_641630526006297879259.so (deleted) 
```
So, we have three mapped instances of the same library, each about 222,4 Mb size in the memory. I suppose it is a quite big overhead and possible (I do not know Netty very well) to cause a memory leak, because all of these files are deleted from the disk.
I've tried to repeat it locally (on AMD64 emulated image, because I am using Macbook Pro M1Pro):
```
# ps -auxw | grep zeebe
root         8  153 11.6 9832980 936700 ?      Sl   06:45   2:52 /usr/bin/qemu-x86_64 /opt/java/openjdk/bin/java /opt/java/openjdk/bin/java -XX:+ExitOnOutOfMemoryError -Dfile.encoding=UTF-8 -Xshare:auto -classpath /usr/local/zeebe/config:/usr/local/zeebe/lib/* -Dapp.name=broker -Dapp.pid=8 -Dapp.repo=/usr/local/zeebe/lib -Dapp.home=/usr/local/zeebe -Dbasedir=/usr/local/zeebe io.camunda.zeebe.broker.StandaloneBroker
root       194  0.0  0.0 148216  7168 pts/0    Sl+  06:47   0:00 /usr/bin/qemu-x86_64 /usr/bin/grep grep zeebe
# cat /proc/8/maps | grep netty
4236200000-4236212000 r--p 00000000 fe:01 400896                         /tmp/libnetty_transport_native_epoll_x86_6414204389556794105758.so (deleted)
4236212000-4236411000 ---p 00012000 fe:01 400896                         /tmp/libnetty_transport_native_epoll_x86_6414204389556794105758.so (deleted)
4236411000-4236414000 r--p 00011000 fe:01 400896                         /tmp/libnetty_transport_native_epoll_x86_6414204389556794105758.so (deleted)
# 
```
Same problem.

**To Reproduce**
1. You need an AMD64 environment or some sort of emulation of it.
2. Consider using this docker-compose file (a little bit modified version of `docker-compose.yml` in this project):
```yml
version: '3'

volumes:
    broker_1: {}
    broker_2: {}
    broker_3: {}

services:

    broker-1:
        image: camunda/zeebe:${ZEEBE_VERSION:-latest}
        ports:
            - 26510:26500
        environment:
            - ZEEBE_LOG_LEVEL=${ZEEBE_LOG_LEVEL:-debug}
            - ZEEBE_BROKER_CLUSTER_NODEID=0
            - ZEEBE_BROKER_CLUSTER_PARTITIONSCOUNT=3
            - ZEEBE_BROKER_CLUSTER_CLUSTERSIZE=3
            - ZEEBE_BROKER_CLUSTER_REPLICATIONFACTOR=3
            - ZEEBE_BROKER_GATEWAY_ENABLE=false
        volumes:
            - broker_1:/usr/local/zeebe/data

    broker-2:
        image: camunda/zeebe:${ZEEBE_VERSION:-latest}
        ports:
            - 26520:26500
        environment:
            - ZEEBE_LOG_LEVEL=${ZEEBE_LOG_LEVEL:-debug}
            - ZEEBE_BROKER_CLUSTER_NODEID=1
            - ZEEBE_BROKER_CLUSTER_PARTITIONSCOUNT=3
            - ZEEBE_BROKER_CLUSTER_CLUSTERSIZE=3
            - ZEEBE_BROKER_CLUSTER_REPLICATIONFACTOR=3
            - ZEEBE_BROKER_CLUSTER_INITIALCONTACTPOINTS=broker-1:26502
            - ZEEBE_BROKER_GATEWAY_ENABLE=false
        volumes:
            - broker_2:/usr/local/zeebe/data

    broker-3:
        image: camunda/zeebe:${ZEEBE_VERSION:-latest}
        ports:
            - 26530:26500
        environment:
            - ZEEBE_LOG_LEVEL=${ZEEBE_LOG_LEVEL:-debug}
            - ZEEBE_BROKER_CLUSTER_NODEID=2
            - ZEEBE_BROKER_CLUSTER_PARTITIONSCOUNT=3
            - ZEEBE_BROKER_CLUSTER_CLUSTERSIZE=3
            - ZEEBE_BROKER_CLUSTER_REPLICATIONFACTOR=3
            - ZEEBE_BROKER_CLUSTER_INITIALCONTACTPOINTS=broker-1:26502
            - ZEEBE_BROKER_GATEWAY_ENABLE=false
        volumes:
            - broker_3:/usr/local/zeebe/data

    gateway:
      image: camunda/zeebe:${ZEEBE_VERSION:-latest}
      ports:
        - 26500:26500
      environment:
        - ZEEBE_STANDALONE_GATEWAY=true
        - ZEEBE_GATEWAY_CLUSTER_CONTACT_POINT=broker-1:26502
```
3. Wait until the cluster is up.
4. Run `zbctl status --insecure`
5. Go to the container shell
6. Find Zeebe PID
7. Execute `cat /proc/PID/maps | grep netty`
8. Observe three instances of the same library

**Expected behavior**

I expect the same behavior in the ARM64 architecture: 
```
# ps -auxw | grep zeebe
root         6 49.6  8.2 9719788 666376 ?      Sl   06:55   0:18 /opt/java/openjdk/bin/java -XX:+ExitOnOutOfMemoryError -Dfile.encoding=UTF-8 -Xshare:auto -classpath /usr/local/zeebe/config:/usr/local/zeebe/lib/* -Dapp.name=broker -Dapp.pid=6 -Dapp.repo=/usr/local/zeebe/lib -Dapp.home=/usr/local/zeebe -Dbasedir=/usr/local/zeebe io.camunda.zeebe.broker.StandaloneBroker
root       153  0.0  0.0   3436  1792 pts/0    S+   06:56   0:00 grep zeebe
# cat /proc/6/maps | grep netty
# 
```

**Log/Stacktrace**

N/A

**Environment:**
- OS: AMD64 compatible (Linux, Mac OS Rosetta emulation)
- Zeebe Version: 8.2.15 
- Configuration: 3 Broker nodes, 1 Gateway node (see the docker-compose.yml)
