### ISSUE TITLE
Support back pressure via Go client job worker

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#15554]
**Description**

[As with the Java workers](https://github.com/camunda/zeebe/issues/15168), we want to ensure that Go workers are not overloaded by too many jobs. The main acceptance criteria is that a worker should not receive more jobs at peak than its `MaxJobsActive` parameter.

> [!Note]
> It should be possible to use bounded channels to control the worker back pressure, but let' see when we get there.

**Comment by npepinpe** [comment]
As we suspected, the implementation already supports back pressure out of the box via channels. Since the call to send to a channel blocks once the channel's buffer is full, the receiving go routine will also block, leading to back pressure being reported to the server.

To test this out, I created a new benchmark. We start 150 PI/s as usual using our benchmark process (refresher: start -> task -> end).

We have 1 poor overworked Go worker, which is really `zbctl` in disguise. I added a `--delay` flag to introduce an artificial completion delay in the worker in order to simulate work.

I deploy the worker with a poll interval of 1ms (the standard for our benchmarks), 60 max jobs active, concurrency of 10, and a 50ms delay (again standard for our benchmarks). Pretty much the same parameters as we usually test for the Java client.

Lo and behold:

![image](https://github.com/camunda/zeebe/assets/43373/82630892-381e-4406-b952-3db306dd156b)

You can see that the stream is accurately detected as blocked. The worker's memory consumption is well within acceptable levels (in fact, we could raise the concurrency) and it doesn't crash anymore.

Interestingly, when I increased the concurrency to 60, the worker could handle the complete 150 PI/s without breaking a sweat using barely 16MB of memory.

Increasing the delay to 1s though, we see immediately it's detected as out of capacity (which makes sense, it only has 60 as queue size):

![image](https://github.com/camunda/zeebe/assets/43373/e3f4f91d-9fe7-4504-a459-868cc0217414)

**Comment by npepinpe** [comment]
Here's the Dockerfile I used to build the worker.

```Dockerfile
FROM busybox

RUN printf "#!/bin/sh\n\
DELAY=\${DELAY:-0.5}\n\
sleep \${DELAY}\n\
exit 0\n" > /usr/bin/handler.sh && \
chmod +x /usr/bin/handler.sh

COPY ./dist/zbctl /usr/bin/zbctl
ENTRYPOINT ["/usr/bin/zbctl"]
```

You then run it like this:

```sh
docker run --rm --net host -e DELAY=1 gcr.io/zeebe-io/zbctl:np-jp create worker --insecure benchmark-task --streamEnabled --concurrency 1 --handler "/usr/bin/handler.sh"
```

> [!Note]
> Locally you need `--net host` if you want to access your local running Zeebe, e.g. the one you launched from your IDE.

You can then use a deployment like this:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
        app.kubernetes.io/component: zeebe-client
    spec:
      containers:
      - env:
        # Delay is in seconds
        - name: DELAY
          value: 1
        image: gcr.io/zeebe-io/zbctl:np-jp
        args: [ "create", "worker", "--insecure", "benchmark-task", "--streamEnabled", "--concurrency", "10", "--handler", "/usr/bin/handler.sh", "--pollInterval", "1ms", "--maxJobsActive", "60" ]
        imagePullPolicy: Always
        name: worker
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 500m
            memory: 256Mi
```
