### ISSUE TITLE
Multi-Region Zeebe Cluster Broker Connectivity Issues

### ISSUE THREAD

**Issue by ChrisJBurns** [camunda/zeebe#16985]
We are setting up a single Zeebe Cluster stretched across multiple clusters, but the brokers cannot talk to each other to achieve a consensus on a leader.

As far as we're aware we just have to setup the Initial Contact Points so that requests can correctly get routed. However, we are finding that the Brokers in ClusterA are not able to talk to the Brokers in ClusterB.

This is an example of our ClusterA INITIALCONTACT_POINTS:
`camunda-zeebe-0.camunda-zeebe.camunda.svc:26502,camunda-zeebe-1.camunda-zeebe.camunda.svc:26502,camunda-zeebe-0.other-cluster.internal:26502,camunda-zeebe-1.other-cluster.internal:26502`

In the Zeebe Broker logs in ClusterA we get constant lines like this:
```logs
Poll request to 3 failed: io.atomix.cluster.messaging.MessagingException$NoSuchMemberException: Expected to send a message with subject 'raft-partition-partition-1-poll' to member '3', but member is not known.
```

In the Zeebe Broker logs on ClusterB there are no logs after a while but the first couple are:
```logs
Failed to handle message, host camunda-zeebe-0.camunda-zeebe.camunda.svc:26502 is not a known cluster member
```

Before we rule any of the HAProxy and Istio Virtual Services a possible offender of the issue, we want to verify whether we have setup the correct CONTACT_POINTS. Also, is there anything regarding ADVERTISED_HOST that we need to modify?

### CoreDNS

For what it's worth, I've also set the CONTACT_POINTS URL's in each cluster like the following:
```
zeebe-0.our.domain.internal:26502,zeebe-1.our.domain.internal:26502,zeebe-2.our.domain.internal:26502,zeebe-3.our.domain.internal:26502
```

With CoreDNS rules set to something like
```
        rewrite name zeebe-0.our.domain.internal camunda-zeebe-0.camunda-zeebe.camunda
        rewrite name zeebe-1.our.domain.internal camunda-zeebe-0.our.domain.internal
        rewrite name zeebe-2.our.domain.internal camunda-zeebe-1.camunda-zeebe.camunda
        rewrite name zeebe-3.our.domain.internal camunda-zeebe-1.our.domain.internal
```
But there hasn't been any affect from what we can see.

**Comment by npepinpe** [comment]
ZDP triage:

- Official multi-region support is coming soon with lots of docs, so hopefully that will help you out then.
- In the meantime, we'll try to provide support, but we're busy getting everything out as release is around the corner.

**Comment by ChrisJBurns** [comment]
Also for what it's worth, I did some initial SPIKE work to figure out how to get a 2 region setup and part of that work looks pretty much the same as was [outlined here](https://github.com/camunda/zeebe/tree/dd-evaluate-2-region-latency/2-region-benchmark), so is good to know that I was on the right tracks :) .. For us, a stretch Zeebe Cluster across 2 namespaces worked great, now we're working on the more mature version which is a stretch Zeebe cluster across two Kubernetes clusters, and although connectivity is working fine across the two. It's just that last part of getting all 4 brokers to be healthy (and stay reliably healthy).

**Comment by deepthidevaki** [comment]
@ChrisJBurns You can take a look at https://github.com/camunda-community-hub/camunda-8-helm-profiles/tree/multi-region-active-active/google/multi-region/active-active Note that this is not an official document, so it may not be complete. So use it at your own risk.

**Comment by mayur2281** [comment]
/reopen
Facing similar issues. Exposed both the cluster's coredns service via internal loadbalancer and also the cluster has cilium cni installed with clustermesh so that the cluster can communicate with each other! Able to connect and get ip addresses of cross cluster pods of statefulset with FQDN via ping and nslookup commands.

camunda-values.yaml:

```yaml
global:
  ingress:
    enabled: true
    host: example.com
    annotations: 
      cert-manager.io/cluster-issuer: letsencrypt
      kubernetes.io/tls-acme: "true"
    tls:
      enabled: true
  multiregion:
    regionId: 0
    regions: 2
  identity:
    keycloak:
      url:
        # This will produce the following URL "https://keycloak.stage.svc.cluster.local:8443".
        # Also the host could be outside the Kubernetes cluster like "keycloak.stage.example.com".
        protocol: "http"
        host: "keycloak-staging.keycloak.svc.cluster.local"
        port: "80"
      auth:
        adminUser: "admin"
        existingSecret: "keycloak-credentials"
        existingSecretKey: "admin-password"
      operate:
        redirectUrl: "https://example.com/operate"
  elasticsearch:
    disableExporter: true
zeebeGateway:
  nodeSelector:
    node: camunda
  env:
      # - name: ZEEBE_GATEWAY_CLUSTER_MESSAGECOMPRESSION
      #   value: GZIP
      # - name: ZEEBE_GATEWAY_CLUSTER_MEMBERSHIP_PROBETIMEOUT
      #   value: 500ms
      # - name: ZEEBE_GATEWAY_CLUSTER_MEMBERSHIP_PROBEINTERVAL
      #   value: 2s
  logLevel: ERROR
  replicas: 1
  service:
    type: LoadBalancer
  resources:
    requests:
      cpu: 150m  
zeebe:
  nodeSelector:
    node: camunda 
  clusterSize: 4
  partitionCount: 4
  replicationFactor: 2
  env:
      - name: ZEEBE_BROKER_DATA_SNAPSHOTPERIOD
        value: 5m
      - name: ZEEBE_BROKER_DATA_DISKUSAGECOMMANDWATERMARK
        value: '0.85'
      - name: ZEEBE_BROKER_DATA_DISKUSAGEREPLICATIONWATERMARK
        value: '0.87'
      - name: ZEEBE_BROKER_CLUSTER_INITIALCONTACTPOINTS
        value: camunda-staging-zeebe-0.camunda-staging-zeebe.camunda-east.svc.cluster.local:26502,camunda-staging-dr-zeebe-0.camunda-staging-dr-zeebe.camunda-west.svc.cluster.local:26502,camunda-staging-zeebe-1.camunda-staging-zeebe.camunda-east.svc.cluster.local:26502,camunda-staging-dr-zeebe-1.camunda-staging-dr-zeebe.camunda-west.svc.cluster.local:26502
      - name: ZEEBE_BROKER_EXPORTERS_ELASTICSEARCHREGION0_CLASSNAME
        value: io.camunda.zeebe.exporter.ElasticsearchExporter
      - name: ZEEBE_BROKER_EXPORTERS_ELASTICSEARCHREGION0_ARGS_URL
        value: http://camunda-staging-elasticsearch-master-hl.camunda-east.svc.cluster.local:9200
      - name: ZEEBE_BROKER_EXPORTERS_ELASTICSEARCHREGION1_CLASSNAME
        value: io.camunda.zeebe.exporter.ElasticsearchExporter
      - name: ZEEBE_BROKER_EXPORTERS_ELASTICSEARCHREGION1_ARGS_URL
        value: http://camunda-staging-dr-elasticsearch-master-hl.camunda-west.svc.cluster.local:9200
      # Enable JSON logging for Google Cloud Stackdriver
      # - name: ZEEBE_LOG_APPENDER
      #   value: Stackdriver
      # - name: ZEEBE_LOG_STACKDRIVER_SERVICENAME
      #   value: zeebe
      # - name: ZEEBE_LOG_STACKDRIVER_SERVICEVERSION
      #   valueFrom:
      #       fieldRef:
      #           fieldPath: metadata.namespace
      # - name: ZEEBE_BROKER_CLUSTER_MEMBERSHIP_PROBETIMEOUT
      #   value: 500ms
      # - name: ZEEBE_BROKER_CLUSTER_MEMBERSHIP_PROBEINTERVAL
      #   value: 2s
      # - name: ZEEBE_BROKER_EXPERIMENTAL_RAFT_SNAPSHOTREQUESTTIMEOUT
      #   value: 10s
      # - name: ZEEBE_BROKER_CLUSTER_MESSAGECOMPRESSION
      #   value: GZIP
      # - name: ZEEBE_BROKER_BACKPRESSURE_AIMD_REQUESTTIMEOUT
      #   value: 1s
  pvcSize: 1Gi
  resources:
    requests:
      cpu: 100m  
connectors:
  nodeSelector:
    node: camunda
  resources:
    requests:
      cpu: 100m
optimize:
  enabled: false
operate:
  nodeSelector:
    node: camunda
  env:
    - name: CAMUNDA_OPERATE_BACKUP_REPOSITORYNAME
      value: camunda_backup
  contextPath: "/operate"
  resources:
    requests:
      cpu: 100m
  migration:
    resources:
      requests:
        cpu: 100m
tasklist:
  enabled: false
identity:
  nodeSelector:
    node: camunda
  contextPath: "/identity"
  fullURL: "https://example.com/identity"
  resources:
    requests:
      cpu: 100m
elasticsearch:
  master:
    nodeSelector:
      node: camunda
    replicaCount: 2
    resources:
      requests:
        cpu: 100m
        memory: 500Mi
    persistence:
        size: 15Gi
identityKeycloak:
  enabled: false
```
