### ISSUE TITLE
Iterate over filters for running CI and merge queue in the new mono repository

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#17231]
## Description

When integrating Operate into the repo we started to add path filters for all (or most) workflows. There were different ways to do it, right now we have to specify [when we don't want to run an workflow](https://github.com/camunda/zeebe/blob/main/.github/workflows/zeebe-ci.yml#L11-L14), which can explode (see [this](https://github.com/camunda/zeebe/pull/17101#discussion_r1537770577)) if we add more and more repos, etc. In Operate CI it might make sense to do the reverse and only specify [where it should run.](https://github.com/camunda/zeebe/blob/main/.github/workflows/operate-ci.yml#L11-L21) 

In general, the path filtering seems to be not that much powerful or doesn't work, as we maybe thought. Especially a problem we currently have with merge queues, where path filtering in general is not supported. https://github.com/orgs/community/discussions/45899#discussioncomment-5643259

### Potential solution for merge queue

There is a github action that might be useful and we could try/explore https://github.com/dorny/paths-filter/issues/183

You can define a new job:

```
  files-changed:
    runs-on: [ self-hosted ]
    outputs:
      any: ${{ steps.changes.outputs.any }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          base: ${{ github.event.merge_group.base_ref}}
          ref: ${{ github.event.merge_group.head_ref }}
          filters: |
            ui:
              - 'ui/**'
```

And make sure that the rest of the jobs only run if the check succeeds.
