### ISSUE TITLE
`ZEEBE_GATEWAY_SECURITY_AUTHENTICATION_MODE:none` does not disable Identity-based authentication

### ISSUE THREAD

**Issue by nicpuppa** [camunda/zeebe#18726]
**Describe the bug**

It should be possible to set the env var `ZEEBE_GATEWAY_SECURITY_AUTHENTICATION_MODE=none`, then use the Zeebe REST API without authenticating via Identity/Keycloak as mentioned in our [docs](https://docs.camunda.io/docs/self-managed/zeebe-deployment/security/client-authorization/#camunda-identity-authorization)

**To Reproduce**

- Install using [separated-ingress-values.yaml](https://github.com/daniel-ewing/camunda-platform-helm/blob/SUPPORT-22024/dev-10.0.x-tests/separated-ingress-values.yaml) and helm charts 10.0.5.
- Port forwarding the zeebe-gateway pod
- Try to execute the GET topology REST API with no bearer token: rest.zeebe.c8.dev.local/v1/topology.

The result is a 401 Unauthorized error.

**Expected behavior**

Setting `ZEEBE_GATEWAY_SECURITY_AUTHENTICATION_MODE` to `none` should disable Identity-based authentication.

**Hint**

Customer said that: _If the spring.profiles.active: identity-auth in zeebe-gateway/configmap.yaml is commented-out/deactivated, then the Identity-based authentication is disabled._

**Environment:**

- Camunda version: 8.5
- Helm chart version: 10.0.4

Related to support case [SUPPORT-22024](https://jira.camunda.com/browse/SUPPORT-22024)

**Comment by korthout** [comment]
Likelihood high because it is [documented as such](https://docs.camunda.io/docs/self-managed/zeebe-deployment/security/client-authorization/#camunda-identity-authorization), and severity mid because there is a workaround present.

We should probably resolve this in the helm charts.

**Comment by korthout** [comment]
I believe the culprit is: https://github.com/camunda/camunda-platform-helm/blob/95625f4295bcf141cf434a50f2005f7489aa00d9/charts/camunda-platform-alpha/templates/zeebe-gateway/configmap.yaml#L18-L21

```yaml
{{- if .Values.zeebe.enabled -}}
kind: ConfigMap
metadata:
  name: {{ include "zeebe.fullname.gateway" . }}-configuration
  labels:
    {{- include "zeebe.labels.gateway" . | nindent 4 }}
apiVersion: v1
data:
  gateway-log4j2.xml: |
{{- if .Values.zeebeGateway.log4j2 }}
    {{ .Values.zeebeGateway.log4j2 | indent 4 | trim }}
{{- end }}
{{- if .Values.zeebeGateway.configuration }}
  application.yaml: |
    {{ .Values.zeebeGateway.configuration | indent 4 | trim }}
{{- else }}
  application.yaml: |
    {{- if .Values.global.identity.auth.enabled }}
    spring:
      profiles:
        active: "identity-auth"
```
