### ISSUE TITLE
Make state directory configurable 

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#6044]
**Is your feature request related to a problem? Please describe.**

Currently we have one directory, which we can configure, the data dir. In this directory everything is stored, the logstream, the runtime state and snapshots. Due to couple readings of RocksDB lecture I understood that RocksDB can have really [high write amplification](https://en.wikipedia.org/wiki/Write_amplification#:~:text=Write%20amplification%20(WA)%20is%20an,amount%20intended%20to%20be%20written), which can compete with other writes like log stream, snapshot replication etc.

Ideally we could configure an directory for each purpose, this would allow us in kubernetes or docker to mount different volumes for different things.

**Describe the solution you'd like**

I can configure different paths for log stream, runtime and snapshots.

**Describe alternatives you've considered**

I see no other alternative except leaving as it is.

**Additional context**

**Use Cases:**

_First use case_ we could have an [empty dir](https://kubernetes.io/docs/concepts/storage/volumes/#emptydir) for the runtime state, since we anyway remove this if we restart. If we want to gain further performance we could also put the empty dir into memory. We just need to make sure that we have enough memory.

This would look like this:
```yaml
        volumeMounts:
        - name: config
          mountPath: /usr/local/zeebe/config/application.yaml
          subPath: application.yaml
        - name: config
          mountPath: /usr/local/bin/startup.sh
          subPath: startup.sh
        - name: data
          mountPath: /usr/local/zeebe/data
        - name: exporters
          mountPath: /exporters
        - name: state-data
          mountPath: /state
        - name: runtime-data
          mountPath: /runtime

        securityContext:
          capabilities:
              add:
              - NET_ADMIN
      volumes:
      - name: config
        configMap:
          name: zell-state-runtime-sep-path-zeebe-cluster
          defaultMode: 0744
      - name: exporters
        emptyDir: {}
      - name: runtime-data
        emptyDir:
          medium: Memory
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ReadWriteOnce]
      storageClassName: ssd
      resources:
        requests:
          storage: "128Gi"
  - metadata:
      name: state-data
    spec:
      accessModes: [ReadWriteOnce]
      storageClassName: ssd
      resources:
        requests:
          storage: "128Gi"

```
Even if we haven't enough memory and we restart a lot due to oom kills we gain a performance boost.
![inmemory](https://user-images.githubusercontent.com/2758593/103275430-7200ba00-49c4-11eb-8a0a-d58d60ae64d8.png)

**Base:**
![base](https://user-images.githubusercontent.com/2758593/103275497-9a88b400-49c4-11eb-9322-d6b28bd87d8c.png)

_Second use case_ it would make it possible to replicate the [snapshots via network filesystem (nfs)](https://matthewpalmer.net/kubernetes-app-developer/articles/kubernetes-volumes-example-nfs-persistent-volume.html). With this we might be able to avoid our own snapshot replication stuff.

_Third use case_ we can adjust the disk sizes regarding to there needs, for example for the log stream we don't need to have such a big disk, since when compacting works as expected we have normally not more then 2 or 3 log segments. It more depends here on the performance of google cloud which size we choose, [see here](https://cloud.google.com/compute/docs/disks/performance#ssd_persistent_disk).

_Fourth use case_ if we have a different disk for snapshots we could still take snapshots even if other disks are already full. This might change our current out of disk mechanism.
