### ISSUE TITLE
Can we support strings as node id's?

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#8736]
**Description**

Afaik currently we support only integers as node id's? But I was wondering why this is the case and whether it is really necessary?

Because of that we always need to do some hacky tricks to set the right node id, e.g. in kubernetes

https://github.com/camunda-community-hub/camunda-cloud-helm/blob/main/charts/ccsm-helm/charts/zeebe/templates/configmap.yaml#L11

```yaml
kind: ConfigMap
metadata:
  name: {{ include "zeebe.fullname" . }}
  labels: {{- include "zeebe.labels.broker" . | nindent 4 }}
apiVersion: v1
data:
  startup.sh: |
    #!/usr/bin/env bash
    set -eux -o pipefail
    export ZEEBE_BROKER_CLUSTER_NODEID=${ZEEBE_BROKER_CLUSTER_NODEID:-${K8S_NAME##*-}}
  
    exec /usr/local/zeebe/bin/broker
```

If we could support string then it would be much easier to configure like:

```yaml
        env:
        - name: ZEEBE_BROKER_CLUSTER_NODEID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
```
