### ISSUE TITLE
Use Snyk to check for license issues or dependency vulnerabilities

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#9245]
**Description**

We should integrate Snyk into our CI to check for dependency vulnerabilities and licensing issues.

For licensing issues, refer to https://confluence.camunda.com/pages/viewpage.action?pageId=76485290 to create an appropriate policy.

For vulnerabilities, we want a check which fails when introducing vulnerabilities with `Medium` or higher vulnerabilities. To allow for exceptions when the vulnerability does not affect us, you can use a `.snyk` file which you can create/edit with the Snyk CLI.

We can use the [Snyk GitHub actions](https://github.com/snyk/actions) to help us out here, as they will be more flexible than the basic GitHub integration.

**Comment by npepinpe** [comment]
Hey @megglos, I see the checks are already on PR - is it in testing or is this done? :thinking:

**Comment by megglos** [comment]
Hey @npepinpe ,

thanks for poking here. As a first iteration I just enabled the PR support from the Web UI to raise awareness.

What is missing is:
 [ ] assess the current license policy in place, haven't digged into it yet, the snyk setup relies within the responsibility of the infosec team now, might be a matter of communication only
 [ ] customize fail conditions, right now the options are based on what is configurable in the [web ui of snyk](https://app.snyk.io/org/team-zeebe/manage/integrations/github) it will fail on any vulnerabilities
 [ ] define how we handle vulnerabilities

**Comment by npepinpe** [comment]
Is it only running PR checks or is it running daily checks? Security vulnerabilities can be found after the fact, so we need both. Last I remember, setting up the daily check via the web UI was very manual and cumbersome :(

**Comment by megglos** [comment]
ZDP-Triage:
- needs to be updated, @npepinpe will take care of this
- @npepinpe is already working on this as part of the Snyk work he does currently

**Comment by npepinpe** [comment]
Repurposing this old issue :smiley: 

### Goals

One core value we have in terms of DevEx is that we want to automate our workflows as much as possible. If it's not automated, chances are we will either forget, or make an error.

So we want to:

1. Automate vulnerability checks during CI to avoid including known vulnerabilities as early as possible
2. Automate license checking during CI to avoid including commercially problematic licenses such as GPL
3. Continuously monitor our distributed artifacts to be notified of new vulnerabilities 

> **Note**
> In the future, having automated fixes for these would be best, but for now we will rely on our normal dependency update features.

Let's flesh this out a bit. We want to monitor the following:

- The HEAD of every supported version branch (aka stable) as the development version for that version
- The HEAD of main as the development version for the next version
- For each supported version, the actual release as the production variant of the version; this includes the Docker image, the Java distribution, the clients, and all modules specified in the Maven BOM.

We distinguish between the "production" and "development" mainly because both can be out of sync, and distinguishing between each is useful as we can then be notified of vulnerabilities  on the production variant, that were automatically fixed via dependabot on the development variant, and require a release.

### Automation

There are three main ways to import projects to Snyk. The Web UI (via the GitHub integration), the CLI, and the REST API. The Web UI is not really automate-able, as it is, well, a UI. So we're left with two options: CLI vs REST API.

> **NOTE**
> The REST API is an enterprise plan only feature, but we are on one, so as long as we remain on it, all good.

The [REST API](https://snyk.docs.apiary.io/#introduction/rest-api) allows us to import projects via one of the integrations (e.g. GitHub). The main advantage there is its tight integration with automatic PR fixes, and automated PR checks. The downside with it is there is no client library for it. We have to manually write our own calls with our own authentication. However, perhaps this is a good use case for our REST connector, and we simply integrate this as part of the Zeebe release process. The REST API allows us to import and delete projects, so we could potentially automate everything through it, including deleting projects once a minor version drops off.

The [CLI](https://docs.snyk.io/snyk-cli) is much more straightforward, but is also more limited in what it can do. The CLI lets you test specific projects to automatically obtain SARIF reports about existing vulnerabilities, and also lets you `monitor` your projects. Monitoring will upload a snapshot of your dependency graph (per project) to Snyk, and essentially is the equivalent of the Web UI project import. Snyk will then notify you (via any of the channels) about new vulnerabilities in your dependencies. The advantage of the CLI is it's very easy to integrate into our CI and release process. The downside is that it does not integrate with automated PR checks, fixes, and so on. You can also not delete projects with the CLI, only import them (via the `monitor`) command. Finally, the CLI supports the `.snyk` file, a way to commit your Snyk ignore, exclusion, and trust policies directly with your code. This offers a portable way of propagating ignore rules, which is quite nice, as the web UI does not allow this.

Here is a sample workflow which would test using the CLI:

<details><summary>.github/workflows/snyk.yml</summary>

```yaml
name: Snyk License & Vulnerability Scan

on:
  workflow_dispatch:
    inputs:
      version:
        description: The project version; defaults to the version as defined by the root POM
        required: false
        type: string
      target:
        description: Allows overriding the project target reference directly; defaults to the current branch
        required: false
        type: string
      monitor:
        description: Upload Snyk snapshot instead of test
        required: false
        type: boolean
        default: false
  workflow_call:
    inputs:
      version:
        description: The project version; defaults to the version as defined by the root POM
        required: false
        type: string
      target:
        description: Allows overriding the project target reference directly; defaults to the current branch
        required: false
        type: string
      monitor:
        description: Upload Snyk snapshot instead of test
        required: false
        type: boolean
        default: false

defaults:
  run:
    # use bash shell by default to ensure pipefail behavior is the default
    # see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference
    shell: bash

jobs:
  scan:
    name: Snyk Scan
    # Run on self-hosted to make building Zeebe much faster
    runs-on: [ self-hosted, linux, amd64, "16" ]
    permissions:
      security-events: write # required to upload SARIF files
    steps:
      - name: Install Snyk CLI
        uses: snyk/actions/setup@master
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-zeebe
        with:
          maven-cache-key-modifier: snyk
          secret_vault_secretId: ${{ secrets.VAULT_SECRET_ID }}
          secret_vault_address: ${{ secrets.VAULT_ADDR }}
          secret_vault_roleId: ${{ secrets.VAULT_ROLE_ID }}
      # We need to build the Docker image (and thus the distribution) to scan it
      - uses: ./.github/actions/build-zeebe
        id: build-zeebe
      - uses: ./.github/actions/build-docker
        id: build-docker
        with:
          distball: ${{ steps.build-zeebe.outputs.distball }}
      # Prepares the bash environment for the step which will actually run Snyk, to avoid mixing too
      # much the GitHub Action contexts/syntax and bash itself.
      - name: Build Snyk Environment
        id: info
        run: |
          set -x
          export TARGET=$([[ ! -z '${{ inputs.target }}' ]] && echo '${{ inputs.target }}' || echo "${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}")
          export VERSION=$([[ ! -z '${{ inputs.version }}' ]] && echo '${{ inputs.version }}' || ./mvnw -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec 2>/dev/null)
          export VERSION_TAG=$([[ "${VERSION}" == *-SNAPSHOT ]] && echo 'development' || echo "${VERSION}")
          export LIFECYCLE=$([[ "${VERSION}" == *-SNAPSHOT ]] && echo 'development' || echo 'production')
          echo "SNYK_ARGS=" \
            "--show-vulnerable-paths=all" \
            "--severity-threshold=high" \
            "--org=team-zeebe" \
            "--project-lifecycle=${LIFECYCLE}" \
            "--project-tags=version=${VERSION_TAG}" \
            "--target-reference=${TARGET}" >> $GITHUB_ENV
          echo "SNYK_COMMAND=${{ (inputs.monitor && 'monitor') || 'test' }}" >> $GITHUB_ENV
          echo "SARIF=${{ (inputs.monitor && '') || 'true' }}" >> $GITHUB_ENV
          echo "DOCKER_IMAGE=${{ steps.build-docker.outputs.image }}" >> $GITHUB_ENV
      - name: Run Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        # The script is set up to scan all distributable artifacts: the projects listed in the bom,
        # the Go client, and the official Docker image.
        # If we add things to the BOM, for example, we should also add them here to the
        # JAVA_PROJECTS variable.
        run: |
          # To avoid exiting on the first failure, we instead flip this to 1 as soon as one of the
          # command fails, and return this at the end; anything non 0 will cause the step to fail
          exitCode=0
          JAVA_PROJECTS=(bom bpmn-model clients/java dist exporter-api gateway-protocol-impl protocol)
          # Remember that when called from a sub-shell, the environment/globals are different
          function output() {
            local sarif="$1"
            local name="$2"
            [ "${sarif}" == 'true' ] && echo "--sarif-file-output=sarif-results/${name}.sarif"
          }
          # Print out command if debug logging is enabled
          set -x
          snyk "${SNYK_COMMAND}" --file=clients/go/go.mod --project-name=clients/go ${SNYK_ARGS} "$(output "${SARIF}" 'go')" || exitCode=1
          for project in "${JAVA_PROJECTS[@]}"; do
          snyk "${SNYK_COMMAND}" --file=${project}/pom.xml --project-name=${project} ${SNYK_ARGS} "$(output "${SARIF}" "${project/\//-}")" || exitCode=1
          done
          snyk container "${SNYK_COMMAND}" "${DOCKER_IMAGE}" --file=Dockerfile --project-name=camunda/zeebe --exclude-app-vulns ${SNYK_ARGS} "$(output "${SARIF}" 'docker')" || exitCode=1
          exit "${exitCode}"
      # This makes the result of our test available in GitHub Code Scanning (look for the Snyk tools)
      # You can filter by your PR ID, by branch, etc.
      # This step is only executed if we're testing, as otherwise no SARIF files are emitted
      - name: Upload Snyk results to GitHub Code Scanning
        if: ${{ ! inputs.monitor }}
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: sarif-results/
      - name: Code Scanning summary
        if: ${{ ! inputs.monitor }}
        run: |
          export PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          cat >> $GITHUB_STEP_SUMMARY <<EOF
            ## Result Links
            - [Code scanning (PR)](https://github.com/camunda/zeebe/security/code-scanning?query=pr:${PR_NUMBER}+tool:"Snyk+Container","Snyk+Open+Source"+is:open)
            - [Code scanning (branch)](https://github.com/camunda/zeebe/security/code-scanning?query=branch:${{ github.ref_name }}+tool:"Snyk+Container","Snyk+Open+Source"+is:open)
            - [Snyk projects](https://app.snyk.io/org/team-zeebe/projects)
          EOF
```

</details>


### REST API examples

Importing a project via the REST API follows this flow:

- Submit an import job for the projects you want, under a specific integration (e.g. GitHub, Docker Hub) (one REST call)
- Poll the import job status until failed or successful (one REST call on each poll)
- Add the required version tag to each project (one REST call per project)
- Apply the required attributes to each project (one REST call per project)
As for the REST API
And here is a sample REST command (with the credentials omitted obviously) to import a project:

<details><summary>Import Minor Version</summary>

```
curl -XPOST https://api.snyk.io/v1/org/team-zeebe/integrations/<GITHUB_INTEGRATION_ID>/import  \
  -H 'Content-Type: application/json; charset=utf-8' -H "Authorization: token $SNYK_TOKEN" \
  --data-binary @- <<EOF
  {
    "target": {
      "owner": "camunda",
      "name": "zeebe",
      "branch": "stable/8.0"
    },
    "exclusionGlobs": "target,vendor",
    "files": [
      { "path": "protocol/pom.xml" },
      { "path": "bom/pom.xml" },
      { "path": "clients/java/pom.xml" },
      { "path": "clients/go/go.mod" },
      { "path": "exporter-api/pom.xml" },
      { "path": "dist/pom.xml" },
      { "path": "bpmn-model/pom.xml" }
    ]
  }
EOF
curl -XPOST https://api.snyk.io/v1/org/team-zeebe/integrations/<DOCKER_INTEGRATION_ID>/import \
  -H 'Content-Type: application/json; charset=utf-8' -H "Authorization: token $SNYK_TOKEN" \
  -d '{ "target": { "name": "camunda/zeebe:8.3.0" }] }'
```

</details>

And here's a sample script which would perform the complete import for code projects (i.e. it's missing the Docker import, which would have to be another job):

<details><summary>snyk-import.sh</summary>

```shell
#!/bin/bash -eux

# Secrets to inject
SNYK_TOKEN=""
GITHUB_INTEGRATION_ID=""

function importCodeProjects() {
  curl -s -D - -XPOST "https://api.snyk.io/v1/org/team-zeebe/integrations/$GITHUB_INTEGRATION_ID/import"  \
  -H 'Content-Type: application/json; charset=utf-8' -H "Authorization: token $SNYK_TOKEN" \
  --data-binary @- <<EOF | grep -i '^Location:' | cut -d: -f2- | tr -d "[:space:]"
  {
    "target": {
      "owner": "camunda",
      "name": "zeebe",
      "branch": "stable/8.0"
    },
    "exclusionGlobs": "target,vendor",
    "files": [
      { "path": "protocol/pom.xml" },
      { "path": "bom/pom.xml" },
      { "path": "clients/java/pom.xml" },
      { "path": "clients/go/go.mod" },
      { "path": "exporter-api/pom.xml" },
      { "path": "dist/pom.xml" },
      { "path": "bpmn-model/pom.xml" }
    ]
  }
EOF
}

function pollImport() {
  local jobUrl="$1"
  local status="pending"

  while [ "${status}" != "complete"  ]; do
    status=$(curl -s ${jobUrl} -H 'Accept: application/json' -H "Authorization: token $SNYK_TOKEN" | jq -r '.status')
    if [ "${status}" == "aborted" ] || [ "${status}" == "failed" ]; then
      echo "Import job failed; see ${jobUrl} for more"
      return 1
    fi
    [ "${status}" != "complete" ] && sleep 5 # avoid getting throttled
  done

  return 0
}

function addProjectTag() {
  local projectUrl="$1"
  local version="${2:-development}"
  
  curl -s -XPOST "${projectUrl}/tags" \
    -H 'Accept: application/json' -H 'Content-Type: application/json; charset=utf-8' -H "Authorization: token $SNYK_TOKEN" \
    -d "{\"key\": \"version\", \"value\": \"${version}\"}"
}

function applyProjectAttributes() {
  local projectUrl="$1"
  local lifecycle="${2:-development}"
  
  curl -s -XPOST "${projectUrl}/attributes" \
    -H 'Accept: application/json' -H 'Content-Type: application/json; charset=utf-8' -H "Authorization: token $SNYK_TOKEN" \
    -d "{\"lifecycle\": [\"${lifecycle}\"]}"
}

CODE_JOB_URL=$(importCodeProjects "")
pollImport "${CODE_JOB_URL}"

PROJECT_URLS=$(curl -s ${CODE_JOB_URL} -H 'Accept: application/json' -H "Authorization: token $SNYK_TOKEN" | jq -r '.logs[].projects[].projectUrl')
for project in $PROJECT_URLS; do
  addProjectTag "${project}"
  applyProjectAttributes "${project}"
done
```

</details>

> **Warning**
> Right now, it seems only Group administrators can add tags/attributes. I'm an organization administrator, but I keep getting a 403. Go figure.

Deleting projects would be similar and would require us to fetch the list of projects for a specific grouping (e.g. stable/8.0) and delete them.

### Summary

All in all, neither CLI or REST API is an ideal approach. And I still need to flesh out which approach is best for what we want to achieve.
