### ISSUE TITLE
Feature Toggles

### ISSUE THREAD

**Issue by pihme** [camunda/zeebe#9254]
**Is your feature request related to a problem? Please describe.**
We are using feature toggles more frequently now. But there currently is no standardized way to define a feature toggle.

This makes implementing a feature toggle for a certain feature take more effort than necessary.

**Describe the solution you'd like**
* Implement a template for feature toggles.
* Document how to add/use/test a feature toggle

**Describe alternatives you've considered**
Adding https://www.togglz.org/quickstart.html as a dependency. However, this doesn't integrate nicely with what we have already. Also it would add a number of transitive dependencies.

**Additional context**

**Comment by pihme** [comment]
## Implementation Approach

* Add a new class `FeatureToggleCfg` as child of `ExperimentalCfg` 
* Add documentation to config templates, add JavaDoc comments to explain how to add a feature toggle

This assumes that feature toggles are only temporary (that's why it's under experimental configuration)

**Comment by npepinpe** [comment]
Looks good to me. What would that look like in practice?

```yaml
zeebe:
  broker:
    experimental:
      features:
        myCoolFeature: false
```

or

```yaml
zeebe:
  broker:
    experimental:
      flags:
        myCoolFeatureFlag: false
```

So all environment variables would also be something like `ZEEBE_BROKER_EXPERIMENTAL_FLAGS_MYCOOLFEATUREFLAG` or the likes?
